### ISSUE TITLE
Plz add my Cheat mod :) https://github.com/RebornTrack970/Extra-Sand

### ISSUE THREAD

**Issue by RebornTrack970** [SimonWoodburyForget/mindustry-mods#19]
https://github.com/RebornTrack970/Extra-Sand

**Comment by SimonWoodburyForget** [comment]
The list is automatically generated. You should rename your mod to avoid collisions with existing mods, currently my anti-duplication system is not very smart, so it may fail on some edge cases.

From what I'm seeing you've forked: https://github.com/MEEPofFaith/Extra-Sand, this is all around going to be an issue, because forked projects don't appear in this list: https://github.com/Anuken/MindustryMods/blob/master/mods.json, as forks are just duplicates of existing projects, they don't need to show up in GitHub search results, which are used to generate it.

I recommend creating a new GitHub repository naming it according to your own mod's name, and then configuring/pushing your local Git fork into the new separate repository. You also want to make sure you add the mindustry-mod keywords to your project (topics/description), otherwise the search tools wont be able to find it.

**Comment by RebornTrack970** [comment]
Ok thx also this is not a duplicated mod, i dont know how to program very well so i just changed stuff on someone elses thx i will make another mod and pıt same content.
